services:
  payload:
    image: node:20-alpine
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app/
    command: sh -c "npm run dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:17.2
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
