name: Build and deploy SSR web app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Prune devDependencies
        run: npm prune --production

      - name: Zip artifacts
        run: >-
          zip --must-match -r build.zip build/ node_modules/ package.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: app/build.zip
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set App Service startup command
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: az webapp config set --resource-group attv71 --name attv71-webapp-ssr --startup-file "node build" --output none

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: attv71-webapp-ssr
          package: build.zip

      - name: az logout
        run: az logout
        if: always()