name: Build and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  file-changes:
    name: Check file changes
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      cms: ${{ steps.changes.outputs.cms }}
      infra: ${{ steps.changes.outputs.infra }}
      generic: ${{ steps.changes.outputs.generic }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check file changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            generic:
              - '.github/**'
            cms:
              - 'cms2/**'
            infra:
              - 'infra/**'

  infra:
    name: Deploy infrastructure
    needs: [file-changes]
    # Runs when either relevant files were changed or workflow_dispatch was triggered.
    # This applies even when jobs this depends on were skipped.
    if: >
      github.event_name == 'workflow_dispatch' ||
      (needs.file-changes.outputs.infra == 'true' || needs.file-changes.outputs.generic == 'true') &&
      (! failure() || ! cancelled())
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep configuration
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: infra/main.bicep
          scope: subscription
          region: westeurope
          parameters: cmsDatabaseConnectionString=${{ secrets.CMS_DATABASE_CONNECTION_STRING }} payloadSecret=${{ secrets.PAYLOAD_SECRET }}

      - name: az logout
        run: az logout
        if: always()

  cms:
    name: Build and deploy CMS
    needs: [file-changes, infra]
    # Runs when either relevant files were changed or workflow_dispatch was triggered.
    # This applies even when jobs this depends on were skipped.
    if: >
      github.event_name == 'workflow_dispatch' ||
      (needs.file-changes.outputs.cms == 'true' || needs.file-changes.outputs.generic == 'true') &&
      (! failure() || ! cancelled())
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          # Azure SWA doesn't support node 22 yet (2025-02-17).
          node-version-file: cms2/package.json
          cache: npm
          cache-dependency-path: cms2/package-lock.json


      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            cms2/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install packages
        run: npm ci --prefix 'cms2/'

      - name: Build
        run: npm run build --prefix 'cms2/'

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.CMS_DEPLOYMENT_TOKEN }}
          action: upload
          app_location: 'cms2/'
          api_location: ""
          output_location: ""
          # SWA uses Oryx for building, which is unbearably slow, so the application is built manually.
          skip_app_build: true
          skip_api_build: true

