name: Build and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: read

jobs:
  file-changes:
    name: Check file changes
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      cms: ${{ steps.changes.outputs.cms }}
      infra: ${{ steps.changes.outputs.infra }}
      generic: ${{ steps.changes.outputs.generic }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check file changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            generic:
              - '.github/**'
            cms:
              - 'cms2/**'
            infra:
              - 'infra/**'
            app:
              - 'app2/**'

  infra:
    name: Deploy infrastructure
    needs: [file-changes]
    # Runs when either relevant files were changed or workflow_dispatch was triggered.
    # This applies even when jobs this depends on were skipped.
    if: >
      github.event_name == 'workflow_dispatch' ||
      (needs.file-changes.outputs.infra == 'true' || needs.file-changes.outputs.generic == 'true') &&
      (! failure() || ! cancelled())
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep configuration
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: infra/main.bicep
          scope: subscription
          region: westeurope
          parameters:
            cmsDatabaseConnectionString=${{ secrets.CMS_DATABASE_CONNECTION_STRING }}
            payloadSecret=${{ secrets.PAYLOAD_SECRET }}

      - name: az logout
        run: az logout
        if: always()

  cms:
    name: Build and deploy CMS
    needs: [file-changes, infra]
    # Runs when either relevant files were changed or workflow_dispatch was triggered.
    # This applies even when jobs this depends on were skipped.
    if: >
      github.event_name == 'workflow_dispatch' ||
      (needs.file-changes.outputs.cms == 'true' || needs.file-changes.outputs.generic == 'true') &&
      (! failure() || ! cancelled())
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Azure SWA doesn't support node 22 yet (2025-02-17).
      - name: Use Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version-file: cms2/package.json

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            cms2/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-cms-${{ hashFiles('cms2/**/package-lock.json') }}-${{ hashFiles('cms2/**/*.js', 'cms2/**/*.jsx', 'cms2/**/*.ts', 'cms2/**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-cms-${{ hashFiles('**/package-lock.json') }}-

      - name: Install packages
        run: npm ci --prefix 'cms2/'

      - name: Build
        run: npm run build:standalone --prefix 'cms2/'
        env:
          NITRO_PRESET: azure

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.CMS_DEPLOYMENT_TOKEN }}
          action: upload
          app_location: 'cms2/'
          api_location: ''
          output_location: ''
          # Oryx should automatically detect the standalone build from the previous steps
          skip_app_build: true
          skip_api_build: true

  app:
    name: Build and deploy App
    needs: [file-changes, infra, cms]
    # Runs when either relevant files were changed or workflow_dispatch was triggered.
    # This applies even when jobs this depends on were skipped.
    if: >
      github.event_name == 'workflow_dispatch' ||
      (needs.file-changes.outputs.app == 'true' || needs.file-changes.outputs.generic == 'true') &&
      (! failure() || ! cancelled())
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Azure SWA doesn't support node 22 yet (2025-02-17).
      - name: Use Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version-file: app2/package.json

      - name: Cache Nuxt build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            app2/.nuxt
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-app-${{ hashFiles('app2/**/package-lock.json') }}-${{ hashFiles('app2/**/*.js', 'app2/**/*.jsx', 'app2/**/*.ts', 'app2/**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-app-${{ hashFiles('**/package-lock.json') }}-

      - name: Install packages
        run: npm ci --prefix 'app2/'

      - name: Run linting
        run: npm run lint --prefix 'app2/'

      - name: Build
        run: npm run build:azure --prefix 'app2/'

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.APP_DEPLOYMENT_TOKEN }}
          action: upload
          app_location: 'app2/.output/public'
          api_location: 'app2/.output/server'
          # The application is already built, so this is the same app_location and can be left unset
          output_location: ''
          skip_app_build: true
          skip_api_build: true
