name: Build CMS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cms/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Prune devDependencies
        run: npm prune --production

      - name: Zip artifacts
        run: >-
          zip --must-match -r payloadcms.zip build/ dist/ node_modules/ package*.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: payloadcms
          path: cms/payloadcms.zip
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: payloadcms

      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set App Service startup command
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: az webapp config set --resource-group attv71 --name attv71-cms --startup-file "dist/server.js"

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: attv71-cms
          package: payloadcms.zip

      - name: az logout
        run: az logout
        if: always()