name: Build and deploy CMS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cms/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.CMS_DEPLOYMENT_TOKEN }}
          action: upload
          app_location: './cms2'
          api_location: ""
          output_location: ""

