name: Configure infrastructure

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**/*.bicep'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Bicep configuration
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: infra/main.bicep
          failOnStdErr: false